[package]
name = "project_euler"
authors = ["Alexander Menne <alexander.menne@nextgenerationgeek.de>"]
license = "MIT"
keywords = ["algebra", "algorithms", "mathematics"]
repository = "https://github.com/nextgenerationgeek/project_euler"
version = "0.1.0"
