name: project-euler-rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Problem001
        run: cargo run --bin p001
      - name: Problem002
        run: cargo run --bin p002
      - name: Problem003
        run: cargo run --bin p003
